artifactsmmo_api = ("- enums.py\r\n"
   "  - Sort            "
   "# Needs for method "
   "\'get_all_characters"
   "\' in class \'Game\'"
   "\r\n"
   "  - ContentType     "
   "# Needs for method "
   "\'get_all_maps\' in "
   "class \'Game\'\r\n"
   "  - Type            "
   "# Needs for method "
   "\'get_all_items\' in"
   " class \'Game\'\r\n"
   "  - CraftSkill      "
   "# Needs for method "
   "\'get_all_items\' in"
   " class \'Game\'\r\n"
   "  - Skill           "
   "# Needs for method "
   "\'get_all_resources"
   "\' in class \'Game\'"
   "\r\n"
   "  - Skin            "
   "# Needs for method "
   "\'create_character\'"
   " in class \'MyAccoun"
   "t\'\r\n"
   "  - Slot            "
   "# Needs for methods "
   "\'equip\' and \'uneq"
   "uip\' in class \'MyC"
   "haracter\'\r\n\r\n\r"
   "\n"
   "- api.py\r\n"
   "    # Simple interfa"
   "ce for classes: MyCh"
   "aracter, MyAccount, "
   "Game\r\n"
   "  - Client(token:str"
   "=None, cooldown_hand"
   "ler:bool=True,\r\n"
   "           errors_ha"
   "ndler:bool=True, req"
   "uest_attempts:int=3)"
   "\r\n"
   "    - static generat"
   "e_token(username:str"
   ", password:str, erro"
   "rs_handler:bool=True"
   ",\r\n"
   "                    "
   "        request_atte"
   "mpts:int=3) -> json"
   "\r\n\r\n"
   "  - MyCharacter(toke"
   "n:str, name:str, coo"
   "ldown_handler:bool=T"
   "rue,\r\n"
   "                erro"
   "rs_handler:bool=True"
   ", request_attempts:i"
   "nt=3)\r\n"
   "    - move(x:int, y:"
   "int) -> json\r\n"
   "    - equip(code:str"
   ", slot:Slot) -> json"
   "\r\n"
   "    - unequip(slot:S"
   "lot) -> json\r\n"
   "    - fight() -> jso"
   "n\r\n"
   "    - gather() -> js"
   "on\r\n"
   "    - craft(code:str"
   ", quantity:int=1) ->"
   " json\r\n"
   "    - deposit_bank(c"
   "ode:str, quantity:in"
   "t) -> json\r\n"
   "    - deposit_bank_g"
   "old(quantity:int) ->"
   " json\r\n"
   "    - recycle(code:s"
   "tr, quantity:int=1) "
   "-> json\r\n"
   "    - withdraw_bank("
   "code:str, quantity:i"
   "nt) -> json\r\n"
   "    - withdraw_bank_"
   "gold(quantity:int) -"
   "> json\r\n"
   "    - buy_ge_item(co"
   "de:str, quantity:int"
   ", price:int) -> json"
   "\r\n"
   "    - sell_ge_item(c"
   "ode:str, quantity:in"
   "t, price:int) -> jso"
   "n\r\n"
   "    - accept_new_tas"
   "k() -> json\r\n"
   "    - complete_task("
   ") -> json\r\n"
   "    - exchange_task("
   ") -> json\r\n"
   "    - delete_item(co"
   "de:str, quantity:int"
   ") -> json\r\n\r\n"
   "  - MyAccount(token:"
   "str, errors_handler:"
   "bool=True, request_a"
   "ttempts:int=3)\r\n"
   "    - get_my_charact"
   "ers() -> json\r\n"
   "    - get_bank_items"
   "(item_code:str=None,"
   " page:int=None, size"
   ":int=None) -> json\r"
   "\n"
   "    - get_bank_golds"
   "() -> json\r\n"
   "    - change_passwor"
   "d(password:str) -> j"
   "son\r\n"
   "    - create_charact"
   "er(name:str, skin:Sk"
   "in) -> json\r\n"
   "    - delete_charact"
   "er(name:str) -> json"
   "\r\n\r\n"
   "  - Game(errors_hand"
   "ler:bool=True, reque"
   "st_attempts:int=3)\r"
   "\n"
   "    - get_status() -"
   "> json\r\n"
   "    - get_all_charac"
   "ters(page:int=None, "
   "size:int=None, sort:"
   "Sort=Sort.DEFAULT) -"
   "> json\r\n"
   "    - get_character("
   "name:str) -> json\r"
   "\n"
   "    - get_all_maps(c"
   "ontent_code:str=None"
   ", content_type:Conte"
   "ntType=ContentType.D"
   "EFAULT,\r\n"
   "                   p"
   "age:int=None, size:i"
   "nt=None) -> json\r\n"
   "    - get_map(x:int,"
   " y:int) -> json\r\n"
   "    - get_all_items("
   "craft_material:str=N"
   "one, craft_skill:Cra"
   "ftSkill=CraftSkill.D"
   "EFAULT,\r\n"
   "                    "
   "max_level:int=None, "
   "min_level:int=None, "
   "name:str=None, page:"
   "int=None,\r\n"
   "                    "
   "size:int=None, _type"
   ":Type=Type.DEFAULT) "
   "-> json\r\n"
   "    - get_item(code:"
   "str) -> json\r\n"
   "    - get_all_monste"
   "rs(drop:str=None, ma"
   "x_level:int=None, mi"
   "n_level:int=None, pa"
   "ge:int=None,\r\n"
   "                    "
   "   size:int=None) ->"
   " json\r\n"
   "    - get_monster(co"
   "de:str) -> json\r\n"
   "    - get_all_resour"
   "ces(drop:str=None, m"
   "ax_level:int=None, m"
   "in_level:int=None, p"
   "age:int=None,\r\n"
   "                    "
   "    size:int=None, s"
   "kill:Skill=Skill.DEF"
   "AULT) -> json\r\n"
   "    - get_resource(c"
   "ode:str) -> json\r\n"
   "    - get_all_events"
   "(page:int=None, size"
   ":int=None) -> json\r"
   "\n"
   "    - get_all_ge_ite"
   "ms(page:int=None, si"
   "ze:int=None) -> json"
   "\r\n"
   "    - get_ge_item(co"
   "de:str) -> json\r\n"
   "    - create_account"
   "(username:str, passw"
   "ord:str, email:str) "
   "-> json\r\n"
   "```\r\n\r\n"
   "### Example\r\n\r\n"
   "```python\r\n"
   "print(self.client.ga"
   "me.get_status())\r\n"
   "print(self.client.ch"
   "aracters[4].move(3, "
   "5))\r\n"
   "print(client.account"
   ".get_my_characters()"
   ")");